### ISSUE TITLE
出力 manifest ファイルについて

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [hymkor/make-scoop-manifest#2]
日本語ですみません。

出力される manifest ファイルですが `checkver` 要素について以下のような内容で出力されます。

```json
    "checkver": {
        "github": "https://github.com/goark/gpgpdump",
        "regex": "tag/([\\d\\._]+)"
    },
```

この内容でも問題なく scoop update できるようですが， `checkver` の要素が [`github` の場合は `regex` が要らない](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases)みたいで， 上の内容でリポジトリに pull request をかけると GitHub Actions の "Pull Requests" でエラーになってしまいます。

方法としては

1. `checkver` の要素が `github` の場合は `regex` 要素を外す
2. GitHub Actions の "Pull Requests" を使わないようにする
 
のいずれかだとだと思いますが， [make-scoop-manifest](https://github.com/hymkor/make-scoop-manifest) 側で `regex` 要素を外すことは可能でしょうか？

**Comment by hymkor** [comment]
OKです。GitHub の Release 機能を使っている場合は、 `"checkver": "github"` だけでいい感じなんですね

**Comment by hymkor** [comment]
対応してみました。どうでしょう

https://github.com/hymkor/make-scoop-manifest/releases/tag/v0.2.1

（一応、hymkor/scoop-bucket へも反映済み）

**Comment by spiegel-im-spiegel** [comment]
こちらも大丈夫でした。  GitHub Actions の "Pull Requests" も問題なく通ります。ありがとうございました。
クロースはおまかせします。

**Comment by hymkor** [comment]
確認ありがとうございます。それでは、本件、閉じさせていただきます。
